[package]
name = "hue"
version = "0.1.0"
authors = ["lucashorward <lucas.horward@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.9"
ureq = "0.12"