[package]
name = "hue_cli"
version = "0.1.0"
authors = ["Lucas Horward <lucas.horward@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hue_core = {path = "../hue-core", version = "0.13"}
tokio = "0.2"