name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Core
      run: cd hue-core && cargo build --verbose
    - name: Run tests
      run: cd hue-core && cargo test --verbose
